export const ERROR_CODES = {
  validation: {
    INVALID_NAME: 'VAL001',
    INVALID_RANGE: 'VAL002',
    INVALID_CELL: 'VAL003',
    INVALID_VALUE: 'VAL004',
    INVALID_POSITION: 'VAL005',
    INVALID_FILE: 'VAL006',
    INVALID_URL: 'VAL007',
    INVALID_CONNECTION: 'VAL008',
    INVALID_TRANSFORMATION: 'VAL009'
  },
  transformation: {
    PARSE_ERROR: 'TRF001',
    CONVERSION_ERROR: 'TRF002',
    MAPPING_ERROR: 'TRF003'
  },
  formula: {
    SYNTAX_ERROR: 'FRM001',
    CALCULATION_ERROR: 'FRM002',
    REFERENCE_ERROR: 'FRM003',
    CIRCULAR_REFERENCE: 'FRM004',
    INVALID_ARGUMENT: 'FRM005'
  },
  stream: {
    READ_ERROR: 'STR001',
    WRITE_ERROR: 'STR002',
    MEMORY_ERROR: 'STR003',
    BUFFER_ERROR: 'STR004'
  },
  security: {
    ACCESS_DENIED: 'SEC001',
    INVALID_SIGNATURE: 'SEC002',
    ENCRYPTION_ERROR: 'SEC003',
    INVALID_CERTIFICATE: 'SEC004'
  },
  file: {
    NOT_FOUND: 'FIL001',
    ACCESS_DENIED: 'FIL002',
    INVALID_FORMAT: 'FIL003',
    IO_ERROR: 'FIL004'
  },
  network: {
    CONNECTION_ERROR: 'NET001',
    TIMEOUT: 'NET002',
    INVALID_RESPONSE: 'NET003',
    REQUEST_FAILED: 'NET004'
  },
  data: {
    INVALID_FORMAT: 'DAT001',
    MISSING_REQUIRED: 'DAT002',
    TYPE_MISMATCH: 'DAT003',
    VALIDATION_FAILED: 'DAT004'
  },
  configuration: {
    INVALID_CONFIG: 'CFG001',
    MISSING_REQUIRED: 'CFG002',
    TYPE_MISMATCH: 'CFG003',
    INVALID_OPTION: 'CFG004'
  }
};